### ISSUE TITLE
How to submit Kitti Datasets?

### ISSUE THREAD

**Issue by zhixianGuo** [xiaohaoChen/rrc_detection#10]
Hi ! I'm going to submit my results，But I don't know what the format it is？Can someone tell me how to do? Thanks！

**Comment by jimmy-ren** [comment]
Hi. Please read the documentation of KITTI carefully.

**Comment by zhixianGuo** [comment]
@jimmy-ren   Thank you for your reply! I have read the KITTI documentation. But I don't understand what the format of score?  like 999.72 or 0.999？
        Best regards

![qq 20170601075947](https://cloud.githubusercontent.com/assets/22787653/26659020/59502fa2-46a0-11e7-8ddc-09d69b038277.png)
