### ISSUE TITLE
OOM Issues on attempt to directly train the RRC 

### ISSUE THREAD

**Issue by joonjeon** [xiaohaoChen/rrc_detection#11]
Hello? I'm a student interested in deep learning.

I saw that the RRC ranked top score on KITTI pedestrian (moderate) dataset, so I decided to try it.
Instead of using pre-trained weights of the model, I tried to directly train the whole model in my PC.

The specs of PC is as follows:
- CPU: Intel® Core™ i7-7700
- GPU: NVIDIA® GeForce® GTX 1080Ti
- OS: Ubuntu 16.04

As far as I know, I have successfully followed the instructions until the Train/Eval stage.
But when I try to train the model using `python examples/car/rrc_kitti_car.py`, it creates an error as follows:
```Shell
...
I0601 10:12:32.332195  6292 net.cpp:219] conv3_1 does not need backward computation.
I0601 10:12:32.332197  6292 net.cpp:219] pool2 does not need backward computation.
I0601 10:12:32.332201  6292 net.cpp:219] relu2_2 does not need backward computation.
I0601 10:12:32.332206  6292 net.cpp:219] conv2_2 does not need backward computation.
I0601 10:12:32.332209  6292 net.cpp:219] relu2_1 does not need backward computation.
I0601 10:12:32.332211  6292 net.cpp:219] conv2_1 does not need backward computation.
I0601 10:12:32.332213  6292 net.cpp:219] pool1 does not need backward computation.
I0601 10:12:32.332216  6292 net.cpp:219] relu1_2 does not need backward computation.
I0601 10:12:32.332218  6292 net.cpp:219] conv1_2 does not need backward computation.
I0601 10:12:32.332221  6292 net.cpp:219] relu1_1 does not need backward computation.
I0601 10:12:32.332223  6292 net.cpp:219] conv1_1 does not need backward computation.
I0601 10:12:32.332228  6292 net.cpp:219] data_data_0_split does not need backward computation.
I0601 10:12:32.332233  6292 net.cpp:219] data does not need backward computation.
I0601 10:12:32.332237  6292 net.cpp:261] This network produces output detection_eval
I0601 10:12:32.333675  6292 net.cpp:274] Network initialization done.
I0601 10:12:32.334671  6292 solver.cpp:63] Solver scaffolding done.
I0601 10:12:32.338502  6292 caffe.cpp:129] Finetuning from models/VGGNet/VGG_ILSVRC_16_layers_fc_reduced.caffemodel
I0601 10:12:32.363605  6292 upgrade_proto.cpp:66] Attempting to upgrade input file specified using deprecated input fields: models/VGGNet/VGG_ILSVRC_16_layers_fc_reduced.caffemodel
I0601 10:12:32.363626  6292 upgrade_proto.cpp:69] Successfully upgraded file specified using deprecated input fields.
W0601 10:12:32.363652  6292 upgrade_proto.cpp:71] Note that future Caffe releases will only support input layers and not input fields.
I0601 10:12:32.374488  6292 net.cpp:752] Ignoring source layer drop6
I0601 10:12:32.375072  6292 net.cpp:752] Ignoring source layer drop7
I0601 10:12:32.375077  6292 net.cpp:752] Ignoring source layer fc8
I0601 10:12:32.375079  6292 net.cpp:752] Ignoring source layer prob
I0601 10:12:32.402130  6292 upgrade_proto.cpp:66] Attempting to upgrade input file specified using deprecated input fields: models/VGGNet/VGG_ILSVRC_16_layers_fc_reduced.caffemodel
I0601 10:12:32.402151  6292 upgrade_proto.cpp:69] Successfully upgraded file specified using deprecated input fields.
W0601 10:12:32.402154  6292 upgrade_proto.cpp:71] Note that future Caffe releases will only support input layers and not input fields.
I0601 10:12:32.412477  6292 net.cpp:752] Ignoring source layer drop6
I0601 10:12:32.413045  6292 net.cpp:752] Ignoring source layer drop7
I0601 10:12:32.413053  6292 net.cpp:752] Ignoring source layer fc8
I0601 10:12:32.413054  6292 net.cpp:752] Ignoring source layer prob
I0601 10:12:32.413715  6292 caffe.cpp:219] Starting Optimization
I0601 10:12:32.413722  6292 solver.cpp:282] Solving VGG_KITTI_RRC_2560x768_kitti_car_train
I0601 10:12:32.413725  6292 solver.cpp:283] Learning Rate Policy: step
F0601 10:12:34.882213  6292 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f16575e948a  google::LogMessage::Fail()
    @     0x7f16575e93ce  google::LogMessage::SendToLog()
    @     0x7f16575e8da0  google::LogMessage::Flush()
    @     0x7f16575ec121  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f1657eb38d0  caffe::SyncedMemory::to_gpu()
    @     0x7f1657eb2899  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f1657ea3313  caffe::Blob<>::mutable_gpu_diff()
    @     0x7f1657ee850f  caffe::CuDNNConvolutionLayer<>::Backward_gpu()
    @     0x7f1657eb949b  caffe::Net<>::BackwardFromTo()
    @     0x7f1657eb94ff  caffe::Net<>::Backward()
    @     0x7f1657e424ec  caffe::Solver<>::Step()
    @     0x7f1657e42f6e  caffe::Solver<>::Solve()
    @           0x40b298  train()
    @           0x407400  main
    @     0x7f1656dfe830  (unknown)
    @           0x407ba9  _start
Aborted (core dumped)
```

Out-of-memory issue... Ouch. :(
In fact, I modified the original python script to cope with having only one GPU card,
and according to one of my colleagues the given GTX 1080Ti has specs similar to that of Titan X,
so I am quite sure that it is supposed to work.

Does anybody have ideas on why this is happening?
I would appreciate if you could give a reply as soon as possible, as I'm planning a presentation on demo of this next Friday.

Thanks in advance.

**Comment by lcwbupt** [comment]
If you only have one TITAN X card, you should modify the script rrc_kitti.py.
```
line 118: gpus = "0,1,2,3" -> gpus = "0"
line 123: batch_size = 4   -> batch_size = 1
```
If you have two TITAN X cards, you should modify the script rrc_kitti.py as follow.
```
line 118: gpus = "0,1,2,3" -> gpus = "0,1"
line 123: batch_size = 4   -> batch_size = 2
```
Have you changed as above? I think it's helpful , GTX 1080Ti is same.

**Comment by lcwbupt** [comment]
If you only have one TITAN X card, you should modify the script rrc_kitti.py.
```
line 118: gpus = "0,1,2,3" -> gpus = "0"
line 123: batch_size = 4   -> batch_size = 1
```
If you have two TITAN X cards, you should modify the script rrc_kitti.py as follow.
```
line 118: gpus = "0,1,2,3" -> gpus = "0,1"
line 123: batch_size = 4   -> batch_size = 2
```
Have you changed as above? I think it's helpful , GTX 1080Ti is same.

**Comment by joonjeon** [comment]
Hello? This is joonjeon.

As stated in the original post, I have already changed the python script as
specified in your email.
That's why it is supposed to work, as long as GTX 1080Ti is similar to
Titan X.

Thanks.

2017-06-01 17:36 GMT+09:00 lcwbupt <notifications@github.com>:

**Comment by jimmy-ren** [comment]
Did you use cudnn?

**Comment by joonjeon** [comment]
Yes. I used cuDNN at compile time.

Of course, the latest version (cuDNN 6.0) seems to be incompatible with this repository, so I just used the same version as stated in the markdown instructions.

But it's still no use...:( The network fails to be trained.

**Comment by xiaohaoChen** [comment]
Maybe you can try to set the "branch_num" to 3. It will reduce memory usage. If It still doesn't work, you could send your script to me. My e-mail is xiaohaoc1992@gmail.com.

**Comment by ferrazpedro1** [comment]
Hey guys! I'm having a similar issue, but I'm trying to run on my single GTX 1070 with only 8GB. I've tried to reduce even more batch_size (line #123) and tried to reduce branch_num as well. 

I've had issues like that in other nets because of my CUDNN, but even when I compiled without CUDNN support, same problem happened.

Do you guys have any idea? Is there any other batch I can reduce?

Thanks in advance!

**Comment by xiaohaoChen** [comment]
Hi! You shoud compile the code with cuDNN. @ferrazpedro1

**Comment by joonjeon** [comment]
I have modified branch_num value to 3 as xiaohaoChen suggested,
and it seems like the RRC starts training successfully on KITTI car dataset. :)

But just in case, I'll keep track of the training process and see if any other error pops up.
I'll notify further as soon as training process ends.

**Comment by joonjeon** [comment]
Hi, ferrazpedro1!

It is mentioned that RRC is tested with cuDNN 5.1, and from my experience it is causing build errors with cuDNN 6.0.
So, as previously stated in one of my comments, if you tried to run using 6.0 version of cuDNN, perhaps you should downgrade the version of your cuDNN from 6.0 to 5.1.

Hope this helps.

**Comment by joonjeon** [comment]
Oh, and besides, how many iterations should I run training on this network?
Is the number of iterations fixed? Or may I stop the training anytime when necessary?
(Seems like the training speed is WAY TOO SLOW... took a day and still training)

**Comment by ferrazpedro1** [comment]
@joonjeon, I'm running the training right now using CUDA 8 and cuDNN 5.1 but it's taking quite a long time too. (20h to get to 30k iterations). I'll let it run until 60k iterations, like the model from the paper.
But since I'm using my GTX1070 has only 8GB I had to reduce both rolling_time and branch_num to 1 so the model can fit.
Tomorrow I'll test the model and see if everything went fine!

**Comment by joonjeon** [comment]
@ferrazpedro1 What? Only 20 hours to get 30k iterations? Wow! I didn't know your PC was that fast.
For me, it's been two days since beginning of training and I haven't even got to 10000th iteration yet...
Are there some tips to get the network run faster?

**Comment by ferrazpedro1** [comment]
@joonjeon, running fast was a sweet illusion! haha
I've changed the parameters and the the model seemed to fit within my 8GB GPU memory but turned out the model didn't work at all. I probably changed something that I shouldn't!
I'll review my configs and params and try again.
How was your training?

**Comment by lcwbupt** [comment]
@ferrazpedro1 @joonjeon @xiaohaoChen I know the meaning of rolling_time，but what the role of branch_num?There seems to be no mention of it in the paper. Will modifying branch_num value to 3 or 2 leads to mAP obviously decrease?

**Comment by joonjeon** [comment]
@ferrazpedro1 Well, everything is going well so far, except that it is too slow...

It has been three days now, and it reached 11000th iteration.
I sincerely hope the results closely match to the pre-trained weights posted in github...
Otherwise, guess I'll have to start all over again. -.-;;;

**Comment by joonjeon** [comment]
Seems like everything has gone well so far.
No OOM issues anymore. So I'll close this issue.

**Comment by ferrazpedro1** [comment]
Hey @joonjeon! How are you doing?
Just following this thread, did you get any success training the RRC for cars and pedestrian? 
If positive, do you still have the weights of the pedestrian net? 
I'm comparing the results of some nets but I couldn't test the RRC-Pedestrian because the author did not upload the pedestrian net weights.

Thank you in advance!
