### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by YangBain** [xiaohaoChen/rrc_detection#33]
@jimmy-ren 
Hello,

This work doesn't support NVIDIA 1080, isn't it?

Thank you very much.

Bin Yang

**Comment by xiaohaoChen** [comment]
This code can run on a Nvidia GTX 1080.
But you should reduce the rolling_time and the branch_num, as GTX 1080 has only 8GB memory.

**Comment by YangBain** [comment]
Thank you very much. It works now.
