### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by BolinZhou** [xiaohaoChen/rrc_detection#4]
Hi, our team is deploying your rrc with KITTI data, however, we had came across some of the issues. We ran it on Ubuntu 16.04, with duo Titan X. 

While we run the `rrc_kitti_car.py`
python returned a 

```
> @Ubuntu16-Caffe:~/RRC$ python examples/car/rrc_kitti_car.py
> Traceback (most recent call last):
>   File "examples/car/rrc_kitti_car.py", line 434, in <module>
>     print(net.to_proto(), file=f)
>   File "python/caffe/net_spec.py", line 209, in to_proto
>     top._to_proto(layers, names, autonames)
>   File "python/caffe/net_spec.py", line 100, in _to_proto
>     return self.fn._to_proto(layers, names, autonames)
>   File "python/caffe/net_spec.py", line 164, in _to_proto
>     assign_proto(layer, k, v)
>   File "python/caffe/net_spec.py", line 64, in assign_proto
>     is_repeated_field = hasattr(getattr(proto, name), 'extend')
> AttributeError: 'LayerParameter' object has no attribute 'weight_filler'

```

Do you have any idea where went wrong? Thanks!!

**Comment by xiaohaoChen** [comment]
This bug didn't appear on my computer. So I don't konw why this error occured on your compute. I tested my code on ubuntu 14.04, maybe you can try to run it on Ubuntu 14.04.

**Comment by FostorHUNT** [comment]
same error on my system :<

**Comment by jimmy-ren** [comment]
@FostorHUNT  What is your OS version?

**Comment by FostorHUNT** [comment]
@jimmy-ren  "Linux version 3.10.0-327 .x86_64 (gcc version 4.8.3 (Red Hat 4.8.3-9) (GCC)"

The root of this problem might be version of libboost, just a speculation. The version of my is 1.60, is that different with yours?

**Comment by xiaohaoChen** [comment]
The version of my libboost is 1.54. @FostorHUNT

**Comment by FostorHUNT** [comment]
@xiaohaoChen @jimmy-ren ,  I have replaced my 1.60 boost with version 1.54 and confirmed that is not the reason...
now I changed another computer with one GPU card Tesla M40,  at least it works! but I found that training is two slow...(batch size 1 as you recommended).
I'm curious about your system. Did you use only 4 GPU card for training? how long have you trained this model?

**Comment by xiaohaoChen** [comment]
We trained several days on 4 TITAN X(Maxwell) for 60000 iterations.

**Comment by liyingbo89** [comment]
I use ubuntu 16 and have the same problem. I replaced "param_names = [s for s in dir(layer) if s.endswith('_param')]" with "param_names = [f.name for f in layer.DESCRIPTOR.fields if f.name.endswith('_param')]" in line 36 in file "net_spec.py" in caffe and resolved this issue. The model is running now. I guess it maybe a caffe version issue.

Hope this can help you.

**Comment by xiaohaoChen** [comment]
@liyingbo89 Thank you. I have updated the code as you said.
@BolinZhou Please update the code.

**Comment by Jilliansea** [comment]
@liyingbo89  hello, I use the code to finetune the dataset of DETRAC, which is also a dataset for car detection, but after I train the network for 50000 times, the detector can't detect any objects, the same situation for the model after 5000 times training. Before training, I have modified the size of input to 1024x768 to avoid out of memory, and changed the learn rate from 0.0005 to 0.00001 to avoid the loss changing to NAN. So please help me why the trained detector didn't work? Thank you very much.

**Comment by joonjeon** [comment]
@Jilliansea maybe that's because DETRAC dataset attribute list does not match with that of PASCAL VOC...

**Comment by liyingbo89** [comment]
Maybe @Jilliansea is correct. I never use DETRAC dataset before. And because you changed learn rate smaller, maybe it will take more time to train. You can try keep the learn rate 0.0005 at first and change it smaller when the model become stable.
