### ISSUE TITLE
Results in paper for Table 4 Car(Hard) using ensemble or not?

### ISSUE THREAD

**Issue by XiongweiWu** [xiaohaoChen/rrc_detection#42]
Hi thx for your excellent work. Recently I just validate your provided trained-model and script. After I submit the result to kitti, the result of three difficult levels are:  90.51 %, 89.90 % and 80.68 % respectively. The moderate level result is close to your paper report(Table 3, 89.85%), however the hard level result is far from the expected one(80.68% vs 86.97%). So I wonder what's the experiment settings in your Table 4, also with ensemble model or not ? Can u help me to check, I just run your code without any modification. Thx

**Comment by XiongweiWu** [comment]
#16

**Comment by xiaohaoChen** [comment]
86.97% is the result of ensemble models. 
As KITTI changed the evaluation rule after we submit our paper, the results you get may be different from the reported results in our paper.
