### ISSUE TITLE
error while create voc type labels

### ISSUE THREAD

**Issue by RyuJunHwan** [xiaohaoChen/rrc_detection#44]
i finished the installation process and i have prepared all required dataset of KITTI.
in order to create a voc type label, I modified the  line4 root_dir in the file convertlabels.m in convert_labels folder and executed extract_car_label.sh.
However, the result is that only the label_2car folder is created and a folder named xml doesn't created under this folder. Why?
(The label_2car folder was successfully created with 6,684 .txt files.)

**Comment by RyuJunHwan** [comment]
I solved it by running it with matlab

**Comment by lhyfst** [comment]
I met the same problem. Could you explain it more specific? Which file did you run with matlab to solve the problem? 

Just run converlabels.m in matlab?
