### ISSUE TITLE
Paper Clarification

### ISSUE THREAD

**Issue by tachim2** [xiaohaoChen/rrc_detection#5]
Hi -- what is meant by this line in the paper?

> To overcome this issue and make the bounding box regression more robust, we further discretize the bounding box regression space within a particular feature maps by assigning multiple regressors for it so that each regressor is responsible for an easier task.

**Comment by jimmy-ren** [comment]
In SSD, each group of feature maps will do regression for bounding boxes for a certain size range (e.g. 100 pixels to 200 pixels). Unlike SSD, we further divide the range to several finer ranges and assign different regressors for each fine range respectively.

**Comment by tachim2** [comment]
Thanks @jimmy-ren. It seems to me that that explains some of the improved IOU performance and that it isn't all explained by the RRC. What are your thoughts on this? Did you try an ablation study?

**Comment by jimmy-ren** [comment]
According to our experience recurrence works better when discretizing the regression space.
