### ISSUE TITLE
how to modify resize_width and resize_height

### ISSUE THREAD

**Issue by liangzimei** [xiaohaoChen/rrc_detection#7]
Hello: 
i want to use rrc to train my own data, and my picture is 1280x720,  shoud i modify the net structure?
Can you give some advces? thanks.

**Comment by xiaohaoChen** [comment]
Line 69 & 70 in the script.
> resize_width = 2560
> resize_height = 768      

The values of width and height should be multiples of 128.

**Comment by liangzimei** [comment]
@xiaohaoChen thank you very much, the problem is solved.
